version: '3.4'
services: 
    apollo-configservice:
        image: apolloconfig/apollo-configservice:1.9.1
        depends_on: 
            - apollo-db

    apollo-adminservice:
        image: apolloconfig/apollo-adminservice:1.9.1
        depends_on: 
            - apollo-db
            - apollo-configservice

    apollo-portal:
        image: apolloconfig/apollo-portal:1.9.1
        depends_on: 
            - apollo-db
            - apollo-configservice

    apollo-db:
        image: mysql:5.7
